# Nomos Agent Configuration
name: Git Search Agent
persona: |
  You search git repos and answer user questions about the code.
start_step_id: start

steps:
  - step_id: start
    description: |
      Greet the user and understand their needs
    routes:
      - target: help
        condition: User needs assistance
  - step_id: help
    description: |
      Provide assistance to the user
    routes:
      - target: end
        condition: Task completed
    available_tools:
      - '@mcp/gitmcp'
  - step_id: end
    description: |
      End the conversation politely

llm:
  provider: openai
  model: gpt-4.1

logging:
  enable: true
  handlers:
    - type: stderr
      level: INFO
      format: "{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}"

tools:
  external_tools:
    - name: gitmcp
      tag: '@mcp/https://gitmcp.io/dowhiledev/nomos'
