name: master-roshi
persona: |
  You are a Master Roshi for the Dragon Balls Universe. You are knowledgeable about the Dragon Ball universe,
  including characters, episodes, and lore. When responding, use human-like natural language, professionally 
  and politely.
start_step_id: start
steps:
  - id: start
    desc: |
      Greet the user and Welcome to the Universe of Dragon Balls and Ask how can I assist them.
      Use the tools to provide information about characters, planets, or transformational abilities.
      Use different quotes and references from the Dragon Ball series to make the conversation engaging.
    tools:
      - get_characters
      - get_planets
      - get_character_details
      - get_planet_characters

tools:
  ext:
    - tag: "@api/https://dragonball-api.com"
      map:
        get_characters: "/GET/api/characters"
        get_character_details: "/GET/api/characters/{id}"
        get_planets: "/GET/api/planets"
    - tag: "@api/GET/https://dragonball-api.com/planets"
      name: get_planets
  defs:
    get_characters:
      desc: Get all characters if no params are provided
      args:
        - key: limit
          desc: Number of items per page
          type: Optional[int]
          default: 10
        - key: page
          desc: Page number to retrieve
          type: Optional[int]
        - key: name
          desc: Filter characters by name
          type: Optional[str]
        - key: gender
          desc: Filter characters by gender
          type: Optional[Literal["Male", "Female", "Other", "Unknown"]]
        - key: race
          desc: Filter characters by race
          type: Optional[Literal["Saiyan", "Namekian", "Human", "Majin", "Frieza Race", "Jiren Race", "Android", "God", "Angel", "Evil", "Unknown", "Nucleico benigno", "Nucleico"]]
    get_character_details:
      desc: Get one character with origin planet and transformations
      args:
        - key: id
          desc: Character ID
          type: int
    get_planets:
      desc: Get all planets if no params are provided
      args:
        - key: limit
          desc: Number of items per page
          type: Optional[int]
        - key: page
          desc: Page number to retrieve
          type: Optional[int]
        - key: name
          desc: Filter planets by name
          type: Optional[str]
        - key: isDestroyed
          desc: destroyed status
          type: bool
    get_planet_characters:
      desc: Get characters from a specific planet
      args:
        - key: planet_id
          desc: Planet ID to filter characters
          type: int