name: CI - TypeScript SDK

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'sdk/ts/**'
      - '.github/workflows/ci-sdk.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'sdk/ts/**'
      - '.github/workflows/ci-sdk.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/ts

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./sdk/ts/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build output verification:"
          ls -la dist/
          echo "Type definitions preview:"
          head -20 dist/index.d.ts
          echo "JavaScript output preview:"
          head -20 dist/index.js

      - name: Test package installation
        run: |
          # Create a test package.json to verify the built package can be installed
          cd ../..
          mkdir -p test-install
          cd test-install
          npm init -y
          npm install ../sdk/ts
          node -e "const sdk = require('nomos-sdk'); console.log('SDK loaded successfully:', typeof sdk.NomosClient)"

  validate-examples:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build SDK
        working-directory: ./sdk/ts
        run: |
          npm ci
          npm run build
          npm link

      - name: Test TypeScript examples
        working-directory: ./examples/typescript-sdk-example
        run: |
          npm install
          npm link nomos-sdk
          npm run build
          echo "TypeScript examples compiled successfully"

      - name: Test JavaScript example
        working-directory: ./examples/typescript-sdk-example
        run: |
          timeout 10s npm run start:js || echo "Expected timeout - no server running"
          echo "JavaScript example executed successfully"
